#!/bin/sh
### BEGIN INIT INFO
# Provides:          preserve_links
# Required-Start:
# Required-Stop:     
# Default-Start:     0 6
# Default-Stop:      
# Short-Description: Preserve any links into non-volatile file systems
# Description:
### END INIT INFO

filter_links () {
    local dirname=$1

    echo '#!/bin/sh'
    echo 'echo "Restoring symlinks"'

    while read target; do
	source=$(readlink "${target}")
	[[ "${source}" =~ ^${dirname}/ ]] && echo "ln -svf ${source} ${target}"
    done

    echo 'rm $0'
}

preserve_links () {
    local dir=$1

    echo "Preserving links to /var/config"

    restdir="${dir}/restore.d"

    if [ ! -d "${restdir}" ]; then
	mkdir -m "0755" "${restdir}"
    fi

    links_file=${restdir}/10links

    find / -xdev -type l | filter_links ${dir} > "${links_file}"
    chmod 700 "${links_file}"

    echo "${links_file} containes $(grep -cF " ${dir}" ${links_file}) links to ${dir} to be restored on reinstall"
}

echo "${0}: ${*}"

# We only run during "stop"
test -z "${1}" -o "${1}" == "stop" || exit 0

if [ -f /var/volatile/do_flash_upgrade ]; then
    preserve_links /var/config
    # restore_links /var/oem
fi

exit 0

